### PR TITLE
Step 33 is been changed by me and i am sure that it is correct

### PR DESCRIPTION
**Pull request by Leorium**
i am happy to help you

### CODE REVIEW

**Comment by Leorium** [comment]
i am also a experienced programmer

**Comment by Ishaan0132** [comment]
I just wanna tell u don't make this changes here 
Fork this repo and do it there

**Comment by Leorium** [comment]
shut up
i just tried to help you 
And don't try to act smart i am more experienced in programming though i am new to git
i have created my own 3 AI

**Comment by Ishaan0132** [comment]
What is your PS name?

**Comment by Leorium** [comment]
I am Aakash hyperium
I have not created AI in showdown
I have created them seperately

**Comment by Professor-Oz** [comment]
As @PowerHitter0418 said fork the repository and make your personal changes there. This is a base repository which I meant to be forked, it's not viable to make personal changes in this repository.

Closing now.

**Pull request closed without merging**
