### PR TITLE
Arifin check the logs of config-example.js

### PR DESCRIPTION
**Pull request by sbdh11**
just change the let variable and ip address

### CODE REVIEW

**Comment by sbdh11** [comment]
just update this professor oz

**Comment by Ishaan0132** [comment]
@DeltaCoderr who told u to make these changes?

**Comment by sbdh11** [comment]
Let me do my own thing.

**Comment by Ishaan0132** [comment]
OK your wish 
He won't merge this but

**Comment by sbdh11** [comment]
kk

**Comment by Professor-Oz** [comment]
@DeltaCoderr personal changes shouldn't be made in base repository.

Closing now.

**Pull request closed without merging**
